version: '3.8'

networks:
  grafana:
  prometheus:

services:
  prometheus:
    image: prom/prometheus:v2.33.5
    command: --web.enable-remote-write-receiver --config.file=/etc/prometheus/prometheus.yml
    networks:
      - grafana
      - prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss
    networks:
      - grafana
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana-config/dashboards:/var/lib/grafana/dashboards
      - ./grafana-config/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-config/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml